"""Run the full AFFEC analysis pipeline from Python modules."""
import argparse
import json
from pathlib import Path
import sys
import time

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import pandas as pd

from affec.data.loader import AFFECDataLoader
from affec.features.extractor import MultimodalFeatureExtractor
from affec.models.baseline import BaselineModel, report_cv_results
from affec.utils.config import Config
from affec.utils.logging import ExperimentLogger


MODALITY_PRESETS = {
    "facial_au": {"au": True, "eye": False, "gsr": False, "personality": False},
    "eye": {"au": False, "eye": True, "gsr": False, "personality": False},
    "gsr": {"au": False, "eye": False, "gsr": True, "personality": False},
    "eye_au_gsr": {"au": True, "eye": True, "gsr": True, "personality": False},
    "eye_au_gsr_personality": {"au": True, "eye": True, "gsr": True, "personality": True},
}


def _preset_label(name: str) -> str:
    labels = {
        "facial_au": "Facial AUs",
        "eye": "Eye-Tracking",
        "gsr": "GSR",
        "eye_au_gsr": "Multimodal (Eye+AU+GSR)",
        "eye_au_gsr_personality": "Multimodal + Personality",
    }
    return labels.get(name, name)


def _write_modality_sweep_report(path: Path, results_by_modality: dict) -> None:
    lines = [
        "# AFFEC Modality Sweep Summary",
        "",
        "Reference baseline results across modality configurations.",
        "",
    ]

    for preset_name, target_results in results_by_modality.items():
        lines.append(f"## {_preset_label(preset_name)} ({preset_name})")
        lines.append("")
        lines.append("| Target | Macro-F1 (mean±std) | Accuracy (mean±std) |")
        lines.append("|---|---:|---:|")
        for target, res in target_results.items():
            lines.append(
                f"| {target} | {res.get('f1_macro_mean', float('nan')):.3f}±{res.get('f1_macro_std', float('nan')):.3f} | "
                f"{res.get('accuracy_mean', float('nan')):.3f}±{res.get('accuracy_std', float('nan')):.3f} |"
            )
        lines.append("")

    lines.extend([
        "## Notes",
        "- Subject-disjoint grouped CV by participant.",
        "- Metrics include class-wise F1, macro-F1, and accuracy per target.",
        "- EEG baselines are maintained separately (deep model workflow) and are not part of this tabular sweep script.",
    ])

    path.write_text("\n".join(lines), encoding="utf-8")


def _demographics_summary(participants: pd.DataFrame) -> dict:
    out = {
        'n_participants': int(len(participants)),
        'gender_counts': {},
        'gender_percent': {},
        'age_min': None,
        'age_max': None,
        'age_mean': None,
    }
    if 'gender' in participants.columns:
        vc = participants['gender'].astype(str).str.lower().value_counts(dropna=False)
        out['gender_counts'] = {str(k): int(v) for k, v in vc.to_dict().items()}
        out['gender_percent'] = {str(k): round(100 * v / len(participants), 2) for k, v in vc.to_dict().items()}
    if 'age' in participants.columns:
        age = pd.to_numeric(participants['age'], errors='coerce').dropna()
        if not age.empty:
            out['age_min'] = float(age.min())
            out['age_max'] = float(age.max())
            out['age_mean'] = float(round(age.mean(), 2))
    return out


def _write_revision_report(report_path: Path, config: Config, demographics: dict, all_results: dict) -> None:
    lines = [
        "# AFFEC Revision Analysis Report",
        "",
        "This report is generated by scripts/run_full_analysis.py to support reviewer-response traceability.",
        "",
        "## Evaluation Setup",
        f"- Cross-validation folds: {config.N_FOLDS}",
        "- Split strategy: subject-disjoint grouped CV by participant",
        f"- EEG window (configured): {config.EEG_WINDOW:.1f}s",
        f"- AU/video analysis window (configured): {config.AU_WINDOW:.1f}s",
        f"- GSR window (configured): {config.GSR_WINDOW:.1f}s",
        "",
        "## Participant Demographics (from participants.tsv)",
        f"- n participants: {demographics.get('n_participants')}",
        f"- gender counts: {demographics.get('gender_counts')}",
        f"- gender percentages: {demographics.get('gender_percent')}",
        f"- age range: {demographics.get('age_min')} to {demographics.get('age_max')} (mean={demographics.get('age_mean')})",
        "",
        "## Target-wise Results",
    ]

    for target, res in all_results.items():
        lines.extend([
            f"### {target}",
            f"- chance level: {res.get('chance_level')}",
            f"- macro-F1: {res.get('f1_macro_mean')} ± {res.get('f1_macro_std')}",
            f"- weighted-F1: {res.get('f1_weighted_mean')} ± {res.get('f1_weighted_std')}",
            f"- accuracy: {res.get('accuracy_mean')} ± {res.get('accuracy_std')}",
            f"- class-wise F1: {res.get('classwise_f1')}",
            f"- stratified metrics: {res.get('stratified_metrics')}",
            "",
        ])

    lines.extend([
        "## Scope Notes",
        "- This revision includes transparent demographic and stratified reporting.",
        "- This revision does not implement domain adaptation/calibration across cohorts.",
        "- This revision does not include external validation on independent datasets.",
    ])

    report_path.write_text("\n".join(lines), encoding='utf-8')


# Per-target optimal-binning thresholds from the notebook (paper-aligned).
# Values: (low_thresh, high_thresh) where 0=low (<=low), 1=medium (<=high), 2=high (>high)
_OPTIMAL_THRESHOLDS = {
    'perceived_arousal': (4.8, 6.0),
    'perceived_valence': (3.8, 5.5),
    'felt_arousal':      (4.6, 6.0),
    'felt_valence':      (4.3, 5.2),
}


def _discretize_target(series: pd.Series, target: str) -> pd.Series:
    """Map continuous 1-9 ratings to 3 ordinal classes using per-target optimal thresholds.

    Class mapping:
        0 = Low  (x <= low_thresh)
        1 = Medium (low_thresh < x <= high_thresh)
        2 = High (x > high_thresh)
    Falls back to equal-width bins for unknown targets.
    """
    s = pd.to_numeric(series, errors='coerce')
    if target in _OPTIMAL_THRESHOLDS:
        lo, hi = _OPTIMAL_THRESHOLDS[target]
        return s.apply(lambda x: pd.NA if pd.isna(x) else (0 if x <= lo else (1 if x <= hi else 2))).astype('Int64')
    # Fallback: equal-width bins
    bins = [0.5, 3.5, 6.5, 9.5]
    return pd.cut(s, bins=bins, labels=[0, 1, 2], include_lowest=True).astype('float').astype('Int64')


def main() -> None:
    parser = argparse.ArgumentParser(description="Run AFFEC full baseline analysis")
    parser.add_argument("--target", default="perceived_arousal", choices=["perceived_arousal", "perceived_valence", "felt_arousal", "felt_valence"])
    parser.add_argument("--all-targets", action="store_true", help="Run all four targets in one pass")
    parser.add_argument(
        "--modality-set",
        default="eye_au_gsr_personality",
        choices=list(MODALITY_PRESETS.keys()),
        help="Modality preset for a single analysis run",
    )
    parser.add_argument(
        "--full-modality-sweep",
        action="store_true",
        help="Run all manuscript-relevant modality presets in one pass",
    )
    parser.add_argument("--max-participants", type=int, default=None, help="Limit participants for a faster smoke run")
    parser.add_argument(
        "--use-autogluon",
        action="store_true",
        help="Use AutoGluon TabularPredictor instead of RandomForest (requires autogluon package)",
    )
    args = parser.parse_args()

    t0 = time.time()
    root = Path(__file__).resolve().parents[1]
    data_dir = root / "data" / "raw"
    loader = AFFECDataLoader(data_dir=str(data_dir))
    config = Config()
    logger = ExperimentLogger(log_dir=str(root / "logs"), experiment_name="affec_full_analysis")
    logger.log_config(config.to_dict())

    participants = loader.load_participants()
    if participants is None:
        raise FileNotFoundError(f"participants.tsv not found under {data_dir}")

    demographics = _demographics_summary(participants)

    participant_ids = participants["participant_id"].dropna().astype(str).tolist()
    if args.max_participants is not None:
        participant_ids = participant_ids[: args.max_participants]

    print(f"Participants to process: {len(participant_ids)}")
    trial_rows = []
    for idx, participant in enumerate(participant_ids, start=1):
        p_start = time.time()
        for run in range(4):
            trial_rows.extend(loader.merge_trial_data(participant, run))
        print(f"[{idx}/{len(participant_ids)}] {participant} done in {time.time()-p_start:.1f}s | trials so far: {len(trial_rows)}")

    if not trial_rows:
        raise RuntimeError("No trial data found. Ensure the Zenodo dataset has been extracted.")

    print(f"Total trials collected: {len(trial_rows)}")

    targets = [args.target]
    if args.all_targets:
        targets = ["perceived_arousal", "perceived_valence", "felt_arousal", "felt_valence"]

    modality_presets = list(MODALITY_PRESETS.keys()) if args.full_modality_sweep else [args.modality_set]

    results_by_modality = {}
    all_reports = []
    all_results_for_revision = {}
    for preset_name in modality_presets:
        modality_cfg = MODALITY_PRESETS[preset_name]
        print(f"\n=== Running preset: {preset_name} | {modality_cfg} ===")
        features = MultimodalFeatureExtractor.extract_batch_features(trial_rows, modality_cfg)

        preset_results = {}
        for target in targets:
            y = _discretize_target(features[target], target).dropna().astype(int)
            X = features.loc[y.index].reset_index(drop=True)
            y = y.reset_index(drop=True)

            print(f"Feature matrix: {X.shape}, target: {target}, labels: {y.shape}")

            model = BaselineModel(
                target=target,
                n_folds=config.N_FOLDS,
                random_state=config.RANDOM_STATE,
                use_autogluon=getattr(args, 'use_autogluon', False),
            )
            results = model.cross_validate(X, y, group_column='participant')
            report = report_cv_results(results, target)
            preset_results[target] = results
            all_reports.append(f"[{preset_name}]\n{report}")
            print(report)

        results_by_modality[preset_name] = preset_results

    # Keep backward compatibility for single-preset runs (revision report expects target->metrics)
    if len(modality_presets) == 1:
        all_results_for_revision = results_by_modality[modality_presets[0]]
    else:
        all_results_for_revision = {
            f"{preset_name}:{target}": res
            for preset_name, target_map in results_by_modality.items()
            for target, res in target_map.items()
        }

    summary_report = "\n\n".join(all_reports)

    report_md_path = root / "logs" / "revision_analysis_report.md"
    _write_revision_report(report_md_path, config=config, demographics=demographics, all_results=all_results_for_revision)

    report_json_path = root / "logs" / "revision_analysis_report.json"
    with open(report_json_path, 'w', encoding='utf-8') as f:
        json.dump({'demographics': demographics, 'results': results_by_modality}, f, indent=2)

    if args.full_modality_sweep:
        sweep_md_path = root / "logs" / "modality_sweep_summary.md"
        sweep_json_path = root / "logs" / "modality_sweep_summary.json"
        _write_modality_sweep_report(sweep_md_path, results_by_modality)
        with open(sweep_json_path, 'w', encoding='utf-8') as f:
            json.dump({'demographics': demographics, 'results': results_by_modality}, f, indent=2)
        print(f"Saved: {sweep_md_path}")
        print(f"Saved: {sweep_json_path}")

    print(f"Total runtime: {time.time()-t0:.1f}s")
    logger.log_results({'demographics': demographics, 'results': results_by_modality})
    logger.add_decision(
        title="Baseline 5-fold evaluation with stratified reporting completed",
        rationale="Supports revision comments with subject-disjoint CV, class-wise F1, and demographic stratified metrics",
        evidence=summary_report,
    )
    logger.add_next_action("If requested by reviewers, add mixed-effects personality models as a separate inferential script.", priority='medium')
    logger.save()


if __name__ == "__main__":
    main()
